# -*- coding: utf-8 -*-
from django.db import models


class TextWebsiteManager(models.Manager):
    def init(self):
        self.get_or_create(name="main_title", content="Revolutionizing the Way people share audio!")
        self.get_or_create(name="main_title_content", content="Yapster is a social networkin app that focuses on audio clips, you can make yaps, listen to other people's yaps and share with friends")
        self.get_or_create(name="main_yap_content", content="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.")
        self.get_or_create(name="main_listen_content", content="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.")
        self.get_or_create(name="main_connect_content", content="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.")
        self.get_or_create(name="main_sign_up_title", content="Sign up for our mailing list to get update!")
        self.get_or_create(name="random_user", content="Niket Jain")
        self.get_or_create(name="random_description", content="Dj of Some Radio")
        self.get_or_create(name="random_opinion", content="")
        self.get_or_create(name="random_text", content="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.")
        self.get_or_create(name="random_small_text", content="Lorem ipsum sit amet, consectetur adipiscing elit. Morbi maximus quam")
        self.get_or_create(name="about_company", content="Yapster is a revolutionary way for people to connect and share with each other using the most basic form of human communication- Audio. ​Yapster allows users a seamless and easy way to create, share and listen to the world using short audio clips. Listen to your favorite yapsters by organizing them by hashtags and groups. Listen to what the world around you is saying")

        Term.objects.get_or_create(name='', title='', content="Yapster, Inc. (\"Yapster,\" \"we,\" \"us,\" or \"our\") offers various services to its users, including, but not limited to, this website (the \"Site\") and its SMS applications and functionalities (the \"Services\"). These Terms of Service (\"Terms\") govern your assess to and use of the Services, and any sound, text, pictures, graphics, information, data, or other materials uploaded, downloaded or otherwise made available on the Services (collectively, \"Content\"). These Terms may be updated by Yapster from time to time without notice to you. By accessing and using the Services, you acknowledge that you have read, understood, and agree to be legally bound by these Terms. You may use the Services only if you can form a legally binding contract with Yapster. If you are entering into these Terms on behalf of a company or other legal entity, you represent that you have the authority to bind such entity to these Terms, in which case the terms \"you\" or \"your\" will refer to such entity. If you do not agree to any of the terms and conditions herein, then please do not use the Services.")
        Term.objects.get_or_create(title="Registration", content="If you would like to use the Services, you will need to become a Registered User by creating an account (\"Account\") with Yapster on this Site. When creating an Account, you must select a unique username (\"Username\") and password (\"Password\"). When creating an Account, you must provide true, accurate, current, and complete information. You are solely responsible for the confidentiality, security, and use of your Account, Username and Password, as well as for any use, misuse, or communications using one or more of them. You will promptly inform Yapster of any need to deactivate your Account, Username or Password. Yapster reserves the right to delete your Account and to delete or change your Password and Username at any time and for any reason. You acknowledge and agree that Yapster will not be liable for any loss or damage caused by any unauthorized use of your Account, Password, or Username.")
        Term.objects.get_or_create(title="User Responsibilities and Guidelines", content="Your use of the Services must comply with these Terms herein, and all applicable federal, state, and local laws, rules, and regulations (collectively, \"Applicable Law\"). You are solely responsible for your access to, and use of, the Services, any Content you make available on the Services (\"Your Content,\" and all other Content hereinafter, \"Third Party Content\"), and any resultant consequences. Your Content may be heard and/or viewed by other users of the Services; thus, you should only provide Content that you are comfortable with sharing publicly with others. By accessing and/or using the Services, you hereby agree that: You will not use the Services for any unlawful purpose;You will not upload, post, e-mail, transmit, or otherwise make available or accessible any Content that:infringes any copyright, trademark, right of publicity, or other proprietary rights of any person or entity; oris threatening, tortious, defamatory, libelous, indecent, obscene, pornographic, sexually explicit, invasive of another’s privacy, or promotes extreme violence or cruelty to animals, or contains hate speech (i.e., speech that attacks or demeans a group based on race or ethnic origin, religion, disability, gender, age, veteran status, and/or sexual orientation/gender identity); ordiscloses any sensitive, confidential, or private information about another person, including that person’s e-mail address, postal address, phone number, credit card information, or any similar information.· You will not harass another person, user or entity;· You will not impersonate another person or entity through the Services in a manner that is likely to confuse or deceive users and other persons, or otherwise misrepresent your relationship and/or affiliation with a person or entity; · You will not use the Services for spamming purposes or for engaging in any pyramid or other multi-tiered marketing scheme;· You will not reverse engineer, decompile, disassemble, or otherwise attempt to discern the source code or interface protocols of the Services;· You will not introduce into the Services any virus, worm, \"back door,\" Trojan Horse, or similar harmful code;· You are solely responsible for obtaining and maintaining all computer hardware, Internet access and other equipment or services needed to access and use the Services and all costs and fees associated therewith. You further acknowledge and agree that the Services may evolve over time, and that as a result, the Services may occasionally change without Yapster providing you advance notice of such change. Additionally, Yapster reserves the right to stop or limit the provision of Services or any of its functionalities to you at any time and for any reason without providing you advance notice.")
        Term.objects.get_or_create(title="Privacy", content="You acknowledge and agree that your use of the Services is also governed by Yapster’s privacy policy (the \"Privacy Policy\"), which is available at www.yapsterapp.com and is incorporated herein by reference. You further acknowledge and agree that through your use of the Services, you consent to the collection and use of your information as set forth in the Privacy Policy.")
        Term.objects.get_or_create(title="Content", content="All Content made available through the Services, whether publicly or privately, is solely attributable to, and the sole responsibility of, the user or person that originated such Content. Yapster does not and cannot monitor or control all Content, and Yapster shall not assume responsibility for any such Content. Your use of, or reliance upon, any Content is undertaken solely at your own risk. Yapster does not make any representations or guarantees regarding the accuracy, authenticity, completeness, or reliability of any Content, and none of the opinions set forth in any Content reflect the opinions of Yapster. You acknowledge and agree that through your use of the Services, you may view and/or hear Content that might be considered offensive, harmful, erroneous, misleading, or inappropriate. Yapster is not obligated to, but reserves the right to, remove any Content that does not adhere to these Terms or that is otherwise unacceptable to us in our sole discretion. You acknowledge and agree that Yapster shall not be liable in any way for any Content, including, but not limited to, any errors or omissions therein, or any damage or losses of any kind incurred as a result of any Content made available on the Services.")
        Term.objects.get_or_create(title="Content Ownership and License", content="You retain ownership of any of Your Content you submit, post, display, or otherwise make available on or through the Services. By making Your Content available through the Services, you grant Yapster a non-exclusive, perpetual, irrevocable, sublicenseable, and royalty-free license to use, copy, reproduce, process, adapt, modify, publish, transmit, display and distribute Your Content throughout the universe in any and all media or distribution methods that are now known or later developed (the \"Content License\"). You represent and warrant that you have the right to provide Your Content through the Services and to grant us the Content License.")
        Term.objects.get_or_create(title="Services Ownership and License", content="Intellectual PropertyYapster grants you a non-exclusive, limited, personal, worldwide, royalty-free, and non-assignable license to access and use the software provided to you by Yapster as part of the Services. Yapster owns all right, title, and interest in and to the Site and the Services, including, without limitation, all trademarks and service marks used in connection with the Site and the Services, and all source code, object code, operating instructions, and interfaces developed for or relating to the same, together with all modifications, enhancements, revisions, changes, copies, partial copies, translations, compilations, improvements, and derivative works thereof, and all intellectual property rights therein (collectively, the \"Yapster Intellectual Property\"). You will have no rights with respect to the Yapster Intellectual Property other than those expressly granted under the License. Additionally, you acknowledge and agree that any comments, suggestions, or feedback (collectively, \"Feedback\") you may provide to Yapster regarding Yapster and/or the Services is entirely voluntary and Yapster shall have the right to use such Feedback in any manner and without any obligation, financial or otherwise, to you.")
        Term.objects.get_or_create(title="Copyright", content="Complaints Yapster respects the intellectual property rights of others, and we ask that you do the same. Yapster complies with the notice and takedown processes set forth by the Digital Millennium Copyright Act (the \"DMCA\"). If you believe the Services contain any Content that infringes your copyright, you may file a copyright complaint (each a \"Copyright Complaint\") with us by sending our designated DMCA agent (our \"DMCA Agent,\" as identified herein) a written communication that: (a) identifies the copyrighted work (the \"Work\") you believe to have been infringed; (b) identifies the material (the \"Material\") that is claimed to infringe upon the Work or that is claimed to be the subject of infringing activity, and information reasonably sufficient that will allow us to locate the Material, including, if possible, a URL(s); (c) provides your contact information, including an address, telephone number and e-mail address; (d) provides a statement that certifies (i) your good faith belief that use of the Material in the manner complained of has not been authorized by the copyright owner, its agent, or Applicable Law, (ii) that the information provided in the Copyright Complaint is accurate, and (iii) under penalty of perjury, that you are authorized to act on behalf of the copyright owner; and (e) provides your physical or electronic signature. Yapster, at our sole discretion, reserves the right to remove and/or disable access to allegedly infringing Content without advance notice to you, and to take any other action it deems appropriate under the circumstances, including terminating your Account. Our designated DMCA Agent is:[i2]")
        Term.objects.get_or_create(title="Term and Termination", content="The Terms will continue to apply until terminated in accordance with this Section. You may terminate these Terms between you and Yapster at any time for any reason by deleting or deactivating your Account and ceasing your access to, and use of, the Services. For the avoidance of doubt, if you reactivate your Account or register for a new account, your access to, and use of, the Services will be governed by the Terms then in effect. In our sole discretion, Yapster has the right to terminate these Terms and suspend or terminate your Account or stop providing you the Services or any functionalities therein for any reason at any time. Yapster will make reasonable efforts to notify you of such suspension or termination. In the event of termination, you will immediately cease all access and use of the Services, and your license to access and use the Services will terminate immediately. The following Sections will survive any termination of these Terms: 2, 4, 5, 6, 8, 9, 10, and 12.")
        Term.objects.get_or_create(title="Disclaimer and Limitation of Liability", content="YOU ACKNOWLEDGE AND AGREE THAT THE SERVICES, INCLUDING, WITHOUT LIMITATION, ALL THIRD PARTY CONTENT, FUNCTIONS AND MATERIALS, ARE PROVIDED \"AS IS,\" \"AS AVAILABLE\", WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. YAPSTER DOES NOT WARRANT THAT THE SERVICES, THIRD PARTY CONTENT, FUNCTIONS OR MATERIALS CONTAINED THEREIN WILL BE TIMELY, SECURE, UNINTERRUPTED OR ERROR FREE, OR THAT DEFECTS WILL BE CORRECTED. YAPSTER SHALL NOT BE LIABLE FOR ANY DAMAGES TO, OR VIRUSES THAT MAY INFECT, YOUR COMPUTER EQUIPMENT OR OTHER PROPERTY ON ACCOUNT OF YOUR ACCESS TO OR USE OF THE SERVICES. IN NO EVENT SHALL YAPSTER BE LIABLE FOR SPECIAL, INDIRECT, PUNITIVE, EXEMPLARY, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, REVENUES OR SAVINGS, EVEN IF YAPSTER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES IN ADVANCE. MOREOVER, IN NO EVENT SHALL THE AGGREGATE LIABILITY OF YAPSTER EXCEED THE GREATER OF ONE HUNDRED U.S. DOLLARS ($100.00) OR THE AMOUNT YOU PAID YAPSTER, IF ANY, IN THE PAST SIX (6) MONTHS FOR THE SERVICES GIVING RISE TO THE CLAIM. BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR NEGLIGENCE, CONSEQUENTIAL, INCIDENTAL OR OTHER DAMAGES, IN SUCH JURISDICTIONS YAPSTER’S LIABILITY IS LIMITED TO THE GREATEST EXTENT PERMITTED BY APPLICABLE LAW. YOUR SOLE AND EXCLUSIVE REMEDY FOR DISSATISFACTION WITH THE SERVICES OR THIRD PARTY CONTENT IS TO STOP USING THE SERVICES. THE LIMITATIONS OF THIS SECTION SHALL APPLY TO ANY THEORY OF LIABILITY, WHETHER BASED ON WARRANTY, CONTRACT, STATUTE, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, AND EVEN IF A REMEDY SET FORTH IN THESE TERMS IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.")
        Term.objects.get_or_create(title="Indemnification", content="To the extent permitted by Applicable Law, you agree to defend, indemnify, and hold harmless Yapster, and its respective officers, directors, employees, and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including, but not limited to, attorney’s fees) arising from: (i) your use and access to the Services, (ii) your violation of any provision of these Terms, (iii) your violation of any third party right, (iv) your negligence or willful misconduct, (v) Your Content, and (vi) your violation of any Applicable Law.")
        Term.objects.get_or_create(title="Third Party Links", content="The Services may contain links to third-party websites (\"External Sites\"). Yapster does not endorse, and is not responsible for, the content of any linked External Sites. Please refer to the terms of use and privacy policies of the External Sites for more information.")
        Term.objects.get_or_create(title="Miscellaneous", content="In the event that any portion of these Terms is held to be invalid or unenforceable, then such portion shall be construed in accordance with Applicable Law as nearly as possible to reflect the original intentions of the parties, and the remainder of these Terms shall remain in full force and effect. You may not assign these Terms. No waiver shall be effective unless in writing. Neither the course of conduct between parties nor trade practice shall act to modify any provision of these Terms. These Terms and any other agreements between the parties entered into through this Site shall be governed by and construed in accordance with the internal, substantive laws of the State of New York, without regard to its conflict of law principles. Except for proceedings commenced by Yapster to protect its intellectual property or confidential information which may be brought in any court of competent jurisdiction, the parties mutually agree that any and all disputes arising hereunder shall be resolved exclusively by state or federal courts located in the State of New York. These Terms contain the entire agreement of the parties concerning the Services and the Content and supersede all existing agreements and all other oral, written or other communication between the parties concerning its subject matter. You shall comply with all laws, rules and regulations which are now or hereinafter promulgated by any government authority or agency which govern or apply to the operation and use of the Services. Questions or comments regarding the Services should be submitted to our email address support@yapsterapp.com or via U.S. mail to 770 Broadway, New York, NY, 10003. We try to respond in a timely manner but are not always able to do so.Effective: [1-24-13] [i1]Please note that these Terms have been drafted under the premise that the Yapster services are provided to users free of charge. If users are subject to a fee, then these terms will need to be modified. [i2]As Yapster is an ISP that will have third party users posting content that is publicly available, this is a highly recommended measure to take in order to provide Yapster a safe harbor under the Copyright Act that can help shield it from copyright infringement liability. We would recommend appointing yourself as the DMCA agent for the time-being. We are happy to provide more detail/context on this DMCA provision on the phone if you would like.")

        Privacy.objects.get_or_create(name="privacy_intro", content="Yapster, Inc. (“Yapster”) respects your privacy and is committed to protecting it. This Privacy Policy describes how Yapster collects, uses and shares your information collected through www.yapster.co (the “Site”) or any Yapster services (the “Services”). Please review this Privacy Policy carefully. By using the Site and/or the Services (collectively, the “Yapster Offerings”), you are accepting the practices described in this Privacy Policy. Please also note that this Privacy Policy may change from time to time. Your continued use of the Yapster Offerings after any such change is deemed to be your acceptance of those changes, so please visit this page and review the Privacy Policy regularly. In this Privacy Policy, the words “we,” “us” and “our” refer to Yapster. Capitalized terms not defined in this Privacy Policy shall have the meaning set forth in our Terms of Service.")
        Privacy.objects.get_or_create(title="Registration Information", content="When you register for our Services, you will be required to provide us certain personally identifiable information (“Personal Data”), including, but not limited to, your name, address, e-mail address, telephone number, username, and password. If you visit the Site, or register for our Services, through Facebook Connect or another social media website, we may also receive certain Personal Data from those social media sites. Some information, like your username, is made publicly available on the Services. Unless you give us permission to do so, we will not sell, license, trade, or rent your Personal Data other than as specified in this Privacy Policy.")
        Privacy.objects.get_or_create(title="Cookies", content="[i1] When you use the Yapster Offerings, we may collect your information, like many websites, through certain automated technology such as cookies. “Cookies” are small packets of data that a website or an application stores on a user’s computer so that the computer will “remember” certain information about the user interaction. Our cookies help provide enhanced functionality for the Yapster Offerings and help us to analyze the use of the Yapster Offerings with greater accuracy. While you have the option of turning cookies off, we recommend that you leave cookies turned on because they allow you to take advantage of some of the Yapster Offerings’ features and functionalities.")
        Privacy.objects.get_or_create(title="Web Server Logs", content="Yapster’s web servers automatically record certain information arising from your use of the Yapster Offerings. Examples of the types of information that we may collect on our servers include your web browser characteristics, IP address, mobile service carrier, device identification, and dates and times you accessed and used the Yapster Offerings. Yapster uses this information in order to provide, analyze and modify the Yapster Offerings, and improve upon them.")
        Privacy.objects.get_or_create(title="External Service Providers", content="[i2] Yapster also uses third party service providers (each a “Service Provider”) that administer various services, such as web analytics and data facilitation, that may use technologies such as cookies, web beacons, and web server logs to assist with analyzing how visitors come upon and use the Yapster Offerings. The information gathered through such means is disclosed to and gathered directly by these Service Providers, and any Service Provider’s use of such information is subject to the Service Provider’s privacy policies, and not Yapster’s. Please contact us at info@yapsterapp.com if you wish to learn more about which third party services we use on the Site, and how you may contact these third party Service Providers.")
        Privacy.objects.get_or_create(title="Yaps and Other Publicly Available Information", content="As you may know, the Services’ main functionality is to allow you to publicly share your Yaps, voice, and audio and text-based messages with others. Much of this information may be widely broadcasted and disseminated. Accordingly, when you share information or content like Yaps, audio, texts, and links through the Services, you should carefully consider what you are making public before making it available on the Services. This Privacy Policy does not apply to any such information or content.")
        Privacy.objects.get_or_create(title="Other Information", content="You may choose to sync a contact list from your mobile device with your Account and the Yapster Offerings in order to allow us to help you find other Yapster users you may know, and vice versa. Additionally, if you connect your Account to another account on a third party service (each an “External Service”), such as Facebook, the External Service may send Yapster additional information such as pictures, names, and birthdays.")
        Privacy.objects.get_or_create(name="second_title", content="Yapster uses the Personal Data you provide in a manner that is consistent with this Privacy Policy. If you provide Personal Data for a certain reason, we may use the Personal Data in connection with the reason for which it was provided. If Yapster intends on using any Personal Data in any manner that is not consistent with this Privacy Policy, you will be informed of such anticipated use prior to or at the time at which the Personal Data is collected.Yapster may use your information to:·Evaluate and respond to your questions and requests;·Tell you about and provide various Yapster products, services and events, which may include some marketing communications;·Help us improve our business by developing new products and services, enhancing our communication abilities, optimizing functionality and user experiences in connection with the Yapster Offerings, and performing marketing and advertising research;·Prevent fraud, unauthorized activities, or anything else that may be harmful;·Comply with applicable laws and this Privacy Policy.")
        Privacy.objects.get_or_create(title="Sharing Your Information", content="[i4] Yapster is not in the business of selling your information, and we will not disclose your information except as described in this Privacy Policy. There are, however, limited circumstances in which we may share your Personal Data with certain third parties without notice to you, which may include disclosing your information as follows: (i) with Service Providers that perform services on our behalf, (ii) with legal authorities if we are compelled to do so by applicable law or an order from a court of competent jurisdiction, (iii) upon request by law enforcement authorities, (iv) if we believe that disclosure is reasonably necessary to prevent physical or financial harm, and (v) in connection with an investigation pertaining to suspected or actual illegal activities. Additionally, in the event of a corporate sale, merger, acquisition, reorganization, bankruptcy, dissolution or similar event (“Transfer Event”), we reserve the right to sell and transfer your Personal Data if we sell or transfer all or a portion of our business or assets. Should a Transfer Event occur, we will use reasonable efforts to direct the transferee to treat your personal information in a manner that is consistent with this Privacy Policy.")
        Privacy.objects.get_or_create(title="Yapster’s Policy Regarding Children", content="Yapster does not knowingly collect personal data from children under the age of 13 through the Yapster Offerings. If you are under 13, please do not give us any Personal Data. We encourage parents and legal guardians to carefully monitor their children's Internet usage and to help enforce our Privacy Policy by instructing their children to never provide Personal Data through the Yapster Offerings without their permission. If you believe that a child under the age of 13 has provided Personal Data to Yapster through the Yapster Offerings, please contact us, and we will endeavor to delete that information from our databases.")
        Privacy.objects.get_or_create(title="Links to External Websites", content="The Yapster Offerings may provide links to other third party websites (“External Websites”) from time to time. This Privacy Policy applies only to the Yapster Offerings, including the Site, and not to any External Websites. We recommend that you contact those sites directly for information on their privacy, security, data collection and distribution policies.")
        Privacy.objects.get_or_create(title="Security ", content="We maintain reasonable security measures intended to protect against the loss, misuse or destruction of Personal Data that we have collected from you in connection with your access to, and use of, the Yapster Offerings. However, we cannot guarantee that the security measures we take will not be circumvented or compromised, or that your Personal Data will remain secure under any and all circumstances.")
        Privacy.objects.get_or_create(title="Updates/Changes to Our Privacy Policy", content="This Privacy Policy is effective as of the date stated at the top of this policy. We may change this Privacy Policy from time to time, and will post any changes on this page. We will also indicate at the top of this page when the changes went into effect. Please be aware that, to the extent permitted by applicable law, our use of information is governed by the Privacy Policy in effect at the time we use the information. Please refer back to this Privacy Policy on a regular basis.")
        Privacy.objects.get_or_create(title="How to Contact Us", content="If you wish to contact us regarding this Privacy Policy, you can reach us at support@yapster.co. [i1]Please verify if you will be using any other tracking technology. [i2]We presume you will be using such third party services, but please confirm. [i3]Please verify if this is accurate / needs additional information. [i4]Please verify if you aggregate data and provide it to third parties in any other manner not covered here, for commercial and/or non-commercial purposes.")

        Article.objects.get_or_create(image="http://127.0.0.1:8000/assets/images/articles/bm.png", title="Lorem ipsum dolor sit amet, consectetur adipiscing elit", content="sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum ")
        Article.objects.get_or_create(image="http://127.0.0.1:8000/assets/images/articles/ubuntu.png", title="Lorem ipsum dolor sit amet, consectetur adipiscing elit", content="sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum ")
        Article.objects.get_or_create(image="http://127.0.0.1:8000/assets/images/articles/vw.png", title="Lorem ipsum dolor sit amet, consectetur adipiscing elit", content="sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum ")

        Opinion.objects.get_or_create(firstname="Niket", lastname="Jain", description="Dj of Some Radio", content="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
        # Privacy.objects.get_or_create(title="random_opinion", content="")
        # self.get_or_create(title="random_opinion", content="")
        # self.get_or_create(title="random_opinion", content="")
        # self.get_or_create(title="random_opinion", content="")
        # self.get_or_create(name="random_opinion", content="")
        # self.get_or_create(name="random_opinion", content="")


class TextWebsite(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=64)
    content = models.TextField(max_length=1024)
    objects = TextWebsiteManager()


class Opinion(TextWebsite):
    firstname = models.CharField(max_length=128)
    lastname = models.CharField(max_length=128)
    description = models.CharField(max_length=128)

class Term(TextWebsite):
    title = models.TextField(max_length=1024, default="")


class Privacy(TextWebsite):
    title = models.TextField(max_length=1024, default="")


class Article(models.Model):
    image = models.FilePathField(path="http://127.0.0.1:8000/assets/images/articles/")
    title = models.CharField(max_length=128)
    content = models.TextField(max_length=1024)